# Generated by Django 3.2.4 on 2021-06-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlaveBot',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=50, unique=True)),
                ('owner_id', models.PositiveIntegerField()),
            ],
        ),
    ]
