# Generated by Django 3.2.4 on 2021-06-19 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_slavebot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.PositiveIntegerField()),
                ('message_id', models.PositiveIntegerField()),
                ('slavebot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.slavebot')),
            ],
        ),
    ]
